title: 路口师傅
logo: /assets/img/logo.png
description: "today is tomorrow."
baidu_analytics: true
theme: jekyll-theme-minimal
lang: CN
url: https://ljyeso.github.io
author: ljyes@outlook.com
permalink: /:categories/:year/:month/:day/:title:output_ext